// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	postgres2 "github.com/gos0001/goauth/internal/adapter/postgres"
	"github.com/gos0001/goauth/internal/controller/admin_v1"
	"github.com/gos0001/goauth/internal/controller/http_v1"
	"github.com/gos0001/goauth/internal/middleware"
	"github.com/gos0001/goauth/internal/orchestrators/bootstrap"
	"github.com/gos0001/goauth/internal/orchestrators/cron"
	"github.com/gos0001/goauth/internal/service/audit"
	"github.com/gos0001/goauth/internal/service/tokens"
	"github.com/gos0001/goauth/internal/usecases/admin/admin_audit_list"
	"github.com/gos0001/goauth/internal/usecases/admin/admin_user_create"
	"github.com/gos0001/goauth/internal/usecases/admin/admin_user_delete"
	"github.com/gos0001/goauth/internal/usecases/admin/admin_user_get"
	"github.com/gos0001/goauth/internal/usecases/admin/admin_user_list"
	"github.com/gos0001/goauth/internal/usecases/admin/admin_user_sessions_list"
	"github.com/gos0001/goauth/internal/usecases/admin/admin_user_sessions_revoke"
	"github.com/gos0001/goauth/internal/usecases/admin/admin_user_set_password"
	"github.com/gos0001/goauth/internal/usecases/admin/admin_user_update"
	"github.com/gos0001/goauth/internal/usecases/audit_cleaner"
	"github.com/gos0001/goauth/internal/usecases/auth/auth_jwks"
	"github.com/gos0001/goauth/internal/usecases/auth/auth_logout_all"
	"github.com/gos0001/goauth/internal/usecases/auth/auth_me"
	"github.com/gos0001/goauth/internal/usecases/auth/auth_password_change"
	"github.com/gos0001/goauth/internal/usecases/auth/auth_register"
	"github.com/gos0001/goauth/internal/usecases/auth/auth_revoke"
	"github.com/gos0001/goauth/internal/usecases/auth/auth_settings"
	"github.com/gos0001/goauth/internal/usecases/auth/auth_token"
	"github.com/gos0001/goauth/internal/usecases/auth/session_list"
	"github.com/gos0001/goauth/internal/usecases/seed_super_admin"
	"github.com/gos0001/goauth/internal/usecases/session_cleaner"
	"github.com/gos0001/goauth/internal/usecases/sys/sys_health"
	"github.com/gos0001/goauth/internal/usecases/webhook_dispatcher"
	"github.com/gos0001/goauth/pkg/cors"
	"github.com/gos0001/goauth/pkg/dbschema"
	"github.com/gos0001/goauth/pkg/logger"
	"github.com/gos0001/goauth/pkg/passwordhash"
	"github.com/gos0001/goauth/pkg/postgres"
	"github.com/gos0001/goauth/pkg/ratelimit"
	"github.com/gos0001/goauth/pkg/realip"
	"github.com/gos0001/goauth/pkg/redis"
	"github.com/gos0001/goauth/pkg/token"
	"github.com/gos0001/goauth/pkg/webhook"
	"github.com/gos0001/goauth/schema"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	config, err := logger.LoadConfig()
	if err != nil {
		return nil, err
	}
	sugaredLogger, err := logger.New(config)
	if err != nil {
		return nil, err
	}
	realipConfig, err := realip.LoadConfig()
	if err != nil {
		return nil, err
	}
	resolver, err := realip.New(realipConfig)
	if err != nil {
		return nil, err
	}
	redisConfig, err := redis.LoadConfig()
	if err != nil {
		return nil, err
	}
	client, err := redis.New(redisConfig)
	if err != nil {
		return nil, err
	}
	ratelimitConfig, err := ratelimit.LoadConfig()
	if err != nil {
		return nil, err
	}
	limiter := ratelimit.New(client, ratelimitConfig)
	tokenConfig, err := token.LoadConfig()
	if err != nil {
		return nil, err
	}
	signer, err := token.New(tokenConfig)
	if err != nil {
		return nil, err
	}
	postgresConfig, err := postgres.LoadConfig()
	if err != nil {
		return nil, err
	}
	pool, err := postgres.New(postgresConfig)
	if err != nil {
		return nil, err
	}
	webhookConfig, err := webhook.LoadConfig()
	if err != nil {
		return nil, err
	}
	adapter := postgres2.New(pool, webhookConfig)
	middlewareConfig, err := middleware.LoadConfig()
	if err != nil {
		return nil, err
	}
	middlewareMiddleware := middleware.New(resolver, limiter, signer, adapter, sugaredLogger, middlewareConfig)
	corsConfig, err := cors.LoadConfig()
	if err != nil {
		return nil, err
	}
	corsMiddleware, err := cors.New(corsConfig)
	if err != nil {
		return nil, err
	}
	limits := http_v1.NewLimits(ratelimitConfig)
	usecase := sys_health.New(pool, client)
	httPv1 := sys_health.NewHTTPv1(usecase, sugaredLogger)
	auth_jwksUsecase := auth_jwks.New(signer)
	auth_jwksHTTPv1 := auth_jwks.NewHTTPv1(auth_jwksUsecase, sugaredLogger)
	auth_settingsConfig, err := auth_settings.LoadConfig()
	if err != nil {
		return nil, err
	}
	auth_settingsUsecase := auth_settings.New(auth_settingsConfig)
	auth_settingsHTTPv1 := auth_settings.NewHTTPv1(auth_settingsUsecase, sugaredLogger)
	issuer := tokens.New(signer, adapter)
	hasher, err := passwordhash.New()
	if err != nil {
		return nil, err
	}
	recorder := audit.New(adapter, sugaredLogger)
	auth_tokenConfig, err := auth_token.LoadConfig()
	if err != nil {
		return nil, err
	}
	auth_tokenUsecase := auth_token.New(adapter, issuer, hasher, limiter, recorder, auth_tokenConfig)
	auth_tokenHTTPv1 := auth_token.NewHTTPv1(auth_tokenUsecase, sugaredLogger)
	auth_registerConfig, err := auth_register.LoadConfig()
	if err != nil {
		return nil, err
	}
	auth_registerUsecase := auth_register.New(adapter, issuer, hasher, recorder, auth_registerConfig)
	auth_registerHTTPv1 := auth_register.NewHTTPv1(auth_registerUsecase, sugaredLogger)
	auth_meUsecase := auth_me.New(adapter)
	auth_meHTTPv1 := auth_me.NewHTTPv1(auth_meUsecase, sugaredLogger)
	session_listUsecase := session_list.New(adapter)
	session_listHTTPv1 := session_list.NewHTTPv1(session_listUsecase, sugaredLogger)
	auth_password_changeConfig, err := auth_password_change.LoadConfig()
	if err != nil {
		return nil, err
	}
	auth_password_changeUsecase := auth_password_change.New(adapter, issuer, hasher, recorder, auth_password_changeConfig)
	auth_password_changeHTTPv1 := auth_password_change.NewHTTPv1(auth_password_changeUsecase, sugaredLogger)
	auth_revokeUsecase := auth_revoke.New(adapter, recorder)
	auth_revokeHTTPv1 := auth_revoke.NewHTTPv1(auth_revokeUsecase, sugaredLogger)
	auth_logout_allUsecase := auth_logout_all.New(adapter, recorder)
	auth_logout_allHTTPv1 := auth_logout_all.NewHTTPv1(auth_logout_allUsecase, sugaredLogger)
	admin_user_createConfig, err := admin_user_create.LoadConfig()
	if err != nil {
		return nil, err
	}
	admin_user_createUsecase := admin_user_create.New(adapter, hasher, recorder, admin_user_createConfig)
	admin_user_createHTTPv1 := admin_user_create.NewHTTPv1(admin_user_createUsecase, sugaredLogger)
	admin_user_listUsecase := admin_user_list.New(adapter)
	admin_user_listHTTPv1 := admin_user_list.NewHTTPv1(admin_user_listUsecase, sugaredLogger)
	admin_user_getUsecase := admin_user_get.New(adapter)
	admin_user_getHTTPv1 := admin_user_get.NewHTTPv1(admin_user_getUsecase, sugaredLogger)
	admin_user_updateUsecase := admin_user_update.New(adapter, recorder)
	admin_user_updateHTTPv1 := admin_user_update.NewHTTPv1(admin_user_updateUsecase, sugaredLogger)
	admin_user_deleteUsecase := admin_user_delete.New(adapter, recorder)
	admin_user_deleteHTTPv1 := admin_user_delete.NewHTTPv1(admin_user_deleteUsecase, sugaredLogger)
	admin_user_set_passwordConfig, err := admin_user_set_password.LoadConfig()
	if err != nil {
		return nil, err
	}
	admin_user_set_passwordUsecase := admin_user_set_password.New(adapter, hasher, recorder, admin_user_set_passwordConfig)
	admin_user_set_passwordHTTPv1 := admin_user_set_password.NewHTTPv1(admin_user_set_passwordUsecase, sugaredLogger)
	admin_user_sessions_listUsecase := admin_user_sessions_list.New(adapter)
	admin_user_sessions_listHTTPv1 := admin_user_sessions_list.NewHTTPv1(admin_user_sessions_listUsecase, sugaredLogger)
	admin_user_sessions_revokeUsecase := admin_user_sessions_revoke.New(adapter, recorder)
	admin_user_sessions_revokeHTTPv1 := admin_user_sessions_revoke.NewHTTPv1(admin_user_sessions_revokeUsecase, sugaredLogger)
	admin_audit_listUsecase := admin_audit_list.New(adapter)
	admin_audit_listHTTPv1 := admin_audit_list.NewHTTPv1(admin_audit_listUsecase, sugaredLogger)
	handlers := admin_v1.NewHandlers(admin_user_createHTTPv1, admin_user_listHTTPv1, admin_user_getHTTPv1, admin_user_updateHTTPv1, admin_user_deleteHTTPv1, admin_user_set_passwordHTTPv1, admin_user_sessions_listHTTPv1, admin_user_sessions_revokeHTTPv1, admin_audit_listHTTPv1)
	engine := http_v1.New(middlewareMiddleware, corsMiddleware, limits, httPv1, auth_jwksHTTPv1, auth_settingsHTTPv1, auth_tokenHTTPv1, auth_registerHTTPv1, auth_meHTTPv1, session_listHTTPv1, auth_password_changeHTTPv1, auth_revokeHTTPv1, auth_logout_allHTTPv1, handlers)
	router := admin_v1.NewRouter(middlewareMiddleware, middlewareConfig, handlers)
	definition := schema.Definition()
	dbschemaConfig, err := dbschema.LoadConfig()
	if err != nil {
		return nil, err
	}
	applier := dbschema.New(pool, definition, dbschemaConfig)
	seed_super_adminConfig, err := seed_super_admin.LoadConfig()
	if err != nil {
		return nil, err
	}
	seed_super_adminUsecase := seed_super_admin.New(adapter, hasher, recorder, seed_super_adminConfig)
	bootstrapBootstrap := bootstrap.New(applier, seed_super_adminUsecase, sugaredLogger)
	audit_cleanerConfig, err := audit_cleaner.LoadConfig()
	if err != nil {
		return nil, err
	}
	audit_cleanerUsecase := audit_cleaner.New(adapter, audit_cleanerConfig)
	cronJob := audit_cleaner.NewCronJob(audit_cleanerUsecase, sugaredLogger, audit_cleanerConfig)
	session_cleanerUsecase := session_cleaner.New(adapter)
	session_cleanerConfig, err := session_cleaner.LoadConfig()
	if err != nil {
		return nil, err
	}
	session_cleanerCronJob := session_cleaner.NewCronJob(session_cleanerUsecase, sugaredLogger, session_cleanerConfig)
	sender := webhook.New(webhookConfig)
	webhook_dispatcherConfig, err := webhook_dispatcher.LoadConfig()
	if err != nil {
		return nil, err
	}
	webhook_dispatcherUsecase := webhook_dispatcher.New(adapter, sender, webhook_dispatcherConfig)
	webhook_dispatcherCronJob := webhook_dispatcher.NewCronJob(webhook_dispatcherUsecase, sugaredLogger, webhook_dispatcherConfig)
	cronCron := cron.New(cronJob, session_cleanerCronJob, webhook_dispatcherCronJob, sugaredLogger)
	mainConfig, err := LoadConfig()
	if err != nil {
		return nil, err
	}
	app := NewApp(sugaredLogger, engine, router, bootstrapBootstrap, cronCron, mainConfig, pool, client)
	return app, nil
}
